server:
  port: 8002
spring:
  application:
    name: provider-ticket


eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka/